<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllEnabledDisabled</name>
   <tag></tag>
   <elementGuidId>de0e7dbd-e8a6-4a92-b689-45893a168884</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='searchSystemUser_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchSystemUser_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cc65b7c9-8144-4b2c-a3d2-bfd78fa56ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchSystemUser[status]</value>
      <webElementGuid>cc87a808-d155-4724-9f79-6bf6e19f5307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchSystemUser_status</value>
      <webElementGuid>09112cf8-857a-44d6-b7d0-42cd1334433c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
All
Enabled
Disabled
</value>
      <webElementGuid>b3032789-7870-4f40-bb26-6e454bba596a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchSystemUser_status&quot;)</value>
      <webElementGuid>a373783b-04f0-41dd-80fd-1f0d980a3ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='searchSystemUser_status']</value>
      <webElementGuid>266005ce-80d1-42ae-9797-e015c8721032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li[4]/select</value>
      <webElementGuid>a699e5e2-ae91-4095-aa42-cf9eb6376234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>2e94a965-6fea-47a6-a353-0c667269d29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Name'])[1]/following::select[1]</value>
      <webElementGuid>a18b6e37-e9c3-4e86-89bb-6abfd73c1b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[2]/preceding::select[1]</value>
      <webElementGuid>c58c2ea6-d272-4712-913e-cdc528496e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Role'])[2]/preceding::select[1]</value>
      <webElementGuid>da53bc9c-49ef-4e87-a06c-e39ba0350022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/select</value>
      <webElementGuid>238c965b-1357-4994-b806-eeea6e81d461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'searchSystemUser[status]' and @id = 'searchSystemUser_status' and (text() = '
All
Enabled
Disabled
' or . = '
All
Enabled
Disabled
')]</value>
      <webElementGuid>1aa19b86-5561-405a-875e-0e90cd761091</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
